### ISSUE TITLE
Test cases observation

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/tck#16]
Hi! We have some observations regarding a few tests cases:

1. This says it is an invalid JSON schema tag, we supposed that it should have a name like “invalid YAML tag”?.
Regardless of this, YAML does not enforce tag existence as validation, so this test should be deleted for us.
https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Format/invalid-json-schema-tag.yaml

2. This test covers an invalid case for discriminator usage deleting “discriminator” facet, but this change does not make the API invalid as discriminator facet is not required for schemas that are being inherited.
https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Schema%20Object/invalid-polymorphism-missing-discriminator.yaml 
Compared to 
https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Schema%20Object/valid-polymorphism.yaml

3. According to JSON Schema spec exclusiveMaximum and exclusiveMinimum MUST be numbers, here are being used as Booleans:
https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Schema%20Object/valid.yaml
Spec: 
https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-6.2.3

Could you review these items?
Thanks!

**Comment by postatum** [comment]
Hi @BlockLucas.

Here where these tests originate from:

**1.** [Format](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#format) section says:
> In order to preserve the ability to round-trip between YAML and JSON formats, YAML version 1.2 is recommended along with some additional constraints:
> * Tags MUST be limited to those allowed by the JSON Schema ruleset

This test showcases usage of an invalid JSON Schema tag, thus making the test invalid.


**2.** I agree that invalidity of that test is questionable due to the way the spec described `descriminator`. I assumed `discriminator` is defined in the parent type (`Pet` in this case) and is required because [this section](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#composition-and-inheritance-polymorphism) says:

> As such, the discriminator field MUST be a required field.

Also I think I've copied most of this test from the [spec example of polymorphism](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#models-with-polymorphism-support).

@fmvilas can you please provide more details on how to use the `discriminator`?


**3.** Good catch. Will fix.

**Comment by BlockLucas** [comment]
Hi!

1. Thanks for pointing that out!
2. I think its right that the spec says that the property used to discriminate types must be in the "required" facet list when discriminator is used, but from what we see, that list of types & their relation are valid even if no discriminator is present, they are just a combination of schemas after all. Pet doesn't really need to check its descendants (the allOf usage on Dog/Cat) to check that a discriminator is needed as in the API you can use any of those types just fine.
3. 👌 

Let me know if I wasn't clear
Regards

**Comment by postatum** [comment]
Hi @BlockLucas.

2. I see what you mean. I understood the part about "required field" as "the `discriminator` field itself is required" as that's what the spec says. Also we have an example of polymorphism which is supported by the `discriminator` field, as the spec says.

I think we should wait for @fmvilas to clarify a usage of this field.

**Comment by fmvilas** [comment]
I agree [this example](https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Schema%20Object/invalid-polymorphism-missing-discriminator.yaml) shouldn't be invalid. It's syntactically correct but semantically incorrect (if polymorphism is what we want to achieve). The `discriminator` field is not required but every "discriminated" field must be.

**Comment by postatum** [comment]
> I agree [this example](https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Schema%20Object/invalid-polymorphism-missing-discriminator.yaml) shouldn't be invalid. It's syntactically correct but semantically incorrect (if polymorphism is what we want to achieve). The `discriminator` field is not required but every "discriminated" field must be.

Understood. Thanks for the clarification!
