### ISSUE TITLE
(Optional case) JSON references in raml types

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/tck#36]
Hi! we are checking the following optional RAML cases

[Message Object/Payloads/valid-optional-raml-api.yaml](https://github.com/asyncapi/tck/tree/master/tests/asyncapi-2.0/Message%20Object/Payloads/valid-optional-raml-api.yaml)
[Message Object/Payloads/valid-optional-raml-datatype.yaml](https://github.com/asyncapi/tck/tree/master/tests/asyncapi-2.0/Message%20Object/Payloads/valid-optional-raml-datatype.yaml)
[Message Object/Payloads/valid-optional-raml-library.yaml](https://github.com/asyncapi/tck/tree/master/tests/asyncapi-2.0/Message%20Object/Payloads/valid-optional-raml-library.yaml)

These are using types referenced like JSON references, which for us is invalid.
I see in the PR in which these tests were added that it was on purpose, is this made as a result of an upcoming clarification either in Async API spec or RAML?

Thanks!

**Comment by postatum** [comment]
Hi @BlockLucas.

What do you mean by "for us is invalid"? Do you mean "not valid in RAML"?

I think these tests are a combination of multiple AsyncAPI spec ideas:
1. "RAML 1.0 data types" are recommended to be supported in Message payload ([spec](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#schema-formats-table)).
2. Reference Objects use JSON References even for YAML-formatted documents. Though YAML-formatted document should be converted to JSON representation ([spec](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#referenceObject)).

---

Not sure how AsyncAPI parsers/tools should behave when handling unusual references:
Should they respect referenced document spec rules? E.g. follow RAML spec when RAML doc is referenced.
OR
Should they convert the referenced doc to JSON and ignore referenced document spec?
Some other way?

**Comment by gutee** [comment]
Hi @postatum.
From AMF we are reviewing which cases we should support from the RAML types section of Async 2.0, we see the logic ones to support is inline RAML types and $ref to a datatype RAML fragment. From the spec it is not clear that those two concepts can be combined, nor they should. RAML does not support JSON Pointers for their types and libraries, so they should not be supported here either. It's a spec thing, if RAML supported this types of references, this should be OK, but it is not so we should correct the cases.

**Comment by jstoiko** [comment]
@gutee: I don't see anything in the AsyncAPI spec that says that JSON references/pointers should be supported within a RAML definition. What it says is that from the perspective of an AsyncAPI definition: `In the case of a YAML-formatted Schema` (and RAML datatypes meets that definition), then `the JSON Reference SHALL be applied to the JSON representation of that schema.` which I read as a way to say that the same referencing mechanism can be applied to both JSON and YAML. 

The three tests linked above reflect use-cases that we think the end-users would benefit from having the AsyncAPI tooling support. The [AsyncAPI+RAML-DT parser](https://github.com/asyncapi/raml-dt-schema-parser) already supports it and I think it would be nice to have supported in AMF as well.

**Comment by antoniogarrote** [comment]
Agree with @jstoiko, RAML types don't support json-refs within the type, but to use it in an AsyncAPI (or OAS) doc, you need to use a JSON-ref.
Async cannot use the library/by-name or the !include mechanisms used in RAML to reference a type.
What we need to clarify on the RAML side is which json-refs are valid when you use RAML Types in non-RAML documents. Can you reference any  RAML document? only libraries (mylib.raml/types/Type)? Can you reference a fragment (myfragment?)

From my point of view, only references to libraries and fragments should be valid. In RAML you cannot reuse inlined types and you cannot reuse types declared in regular API documents.

To reuse library types, I would expect a fixed pointer "{lib}#/types/{typeName}". For fragments "{fragment}".

Also when declaring a RAML type inlined in an AsyncAPI doc, !includes should be valid.

These referencing mechanisms could also be valid in an OAS document referencing types in RAML libraries/fragments.

**Comment by gutee** [comment]
@jstoiko I understand your point on Json Pointers here, it seems that, as the spec is defined now, the user is free to point anywhere he wants, it is not restricted. I believe @antoniogarrote was saying this should be restricted for reusability to make sense.
As for !includes in Async/OAS, Antonio was talking about cases where a reference RAML type is defined inline in the AsyncAPI and you need to reference another RAML type (inheritance for example). He is stating that once you are parsing a RAML type, !includes can be used there to point to another types.

**Comment by jstoiko** [comment]
The AsyncAPI spec does not prescribe how RAML Datatypes should behave when used in combination with AsyncAPI. All the AsyncAPI spec says is that it is recommended to support RAML Datatypes and points to the RAML 1.0 spec's section on  "Datatypes". It doesn't say to what extent a processor should support RAML Datatypes (when it does) however the RAML spec does talk about modularization from the context of Datatypes so if one was to look at it from a literal interpretation, modularization should be an integral part of the "AsyncAPI + RAML Datatype" support.

That being said, if there is a good reason for a given tool not to support modularization in this context, so be it. As a general rule, I don't think "recommended support" is an all or nothing thing, there are situations in which this may translate into "partial support" because it makes the most sense, practically speaking. As long as things are well documented for the end-user and the expectations are set, I don't see this as being an issue. Also, those TCK tests are part of the "recommended" suite of tests and shouldn't affect the total % anyway.

I can see that [asyncapi/raml-dt-schema-parser](https://github.com/asyncapi/raml-dt-schema-parser) uses [raml-org/ramldt2jsonschema](https://github.com/raml-org/ramldt2jsonschema) under the hood (which uses `webapi-parser` and `AMF` under the hood of that 🙃), and the mechanism of how the base path is defaulting to when a RAML Datatype contains external references is [documented there](https://github.com/raml-org/ramldt2jsonschema#resolving-references) too.
